### ISSUE TITLE
[Fixed] rendering on Safari bug

### ISSUE THREAD

**Issue by idkjs** [LXSMNSYC/bs-broadcast-channel#1]
Just an FYI. I have no idea what this means and don't need it. Feel free to close.

I ran your example and made some edits to see test it in the ui.

This is firefox:
<img width="694" alt="Screenshot 2020-01-11 at 1 26 49 PM" src="https://user-images.githubusercontent.com/2370391/72208863-15845200-3476-11ea-8df7-2e14e085edb5.png">

This is Safari:

<img width="1311" alt="Screenshot 2020-01-11 at 1 27 52 PM" src="https://user-images.githubusercontent.com/2370391/72208870-3187f380-3476-11ea-9804-3c1e8af17ccb.png">

Environment:
```sh
➜  example macenv
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57
yarn version: 1.21.1
node version: v13.3.0
```

**Comment by lxsmnsyc** [comment]
thanks for reporting!

It seems that the package I am using is not supposed to be a polyfill but an alternative one (strange tho, I think they advertise it as one)

**Comment by lxsmnsyc** [comment]
Since there isn't much polyfills to be found, the closest I can get is from the package `broadcastchannel-polyfill`.

I just found out that the initial polyfill has different data flow (e.g. MessageEvent only responds with a string)

Currently, the problem here is that Safari doesn't support this feature in the first place (a shame).

I'll mark this as fixed.
